import { defineQuery } from "next-sanity";

export const siteContentQuery = defineQuery(`
  *[_type == "siteContent" && _id == "siteContent"][0]{
    brandName,
    tagline,
    shortAbout,
    heroTitle,
    heroSubtitle,
    heroDescription,
    heroPrimaryCta,
    heroSecondaryCta,
    founderImage{
      asset->{
        url
      }
    },
    logoImage{
      asset->{
        url
      }
    },
    founder{
      name,
      credentials,
      roleLine,
      summary,
      highlights
    },
    services[]{
      _key,
      title,
      description,
      audience,
      mode
    },
    packageSection{
      eyebrow,
      title,
      description,
      categories,
      addOnTitle,
      addOnDescription,
      packages[]{
        _key,
        name,
        category,
        subtitle,
        priceLabel,
        duration,
        isPopular,
        features
      },
      addOns[]{
        _key,
        name,
        priceLabel,
        description
      }
    },
    testimonials[]{
      _key,
      title,
      quote,
      source
    },
    contact{
      title,
      intro,
      phone,
      email,
      location,
      appointmentNote,
      instagram,
      linkedin
    },
    gallery[]{
      _key,
      title,
      image{
        asset->{
          url
        }
      }
    }
  }
`);
